spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/gdou_gms_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: ../pages/
      suffix: .html

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false